name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

# TODO: should bring this back
#      - name: Analyze project source
#        run: flutter analyze

      - name: Run tests
        run: flutter test

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2

      - name: Build APK
        run: flutter build apk

      - name: Build APP Bundle
        run: flutter build appbundle

      - name: Build Web
        run: flutter build web

  package-ios:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter build ios --release --no-codesign
