name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build App Bundle
        run: flutter build appbundle

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: AAB
          path: build/app/outputs/bundle/release/app-release.aab

  package-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Upload iOS App
        uses: actions/upload-artifact@v3
        with:
          name: iOS APP
          path: build/ios/iphoneos/Runner.app
